// Permission keys as `resource.action` (SYSTEM_PROMPT §5, §11 — the RBAC
// vocabulary the backend re-checks on every route). This set grows per feature.
export const PERMISSIONS = {
  USERS_READ: 'users.read',
  USERS_CREATE: 'users.create',
  USERS_UPDATE: 'users.update',
  USERS_DELETE: 'users.delete',
  ROLES_READ: 'roles.read',
  ROLES_MANAGE: 'roles.manage',
  PROJECTS_READ: 'projects.read',
  PROJECTS_CREATE: 'projects.create',
  PROJECTS_UPDATE: 'projects.update',
  PROJECTS_DELETE: 'projects.delete',
  TASKS_READ: 'tasks.read',
  TASKS_CREATE: 'tasks.create',
  TASKS_UPDATE: 'tasks.update',
  TASKS_DELETE: 'tasks.delete',
  MILESTONES_READ: 'milestones.read',
  MILESTONES_CREATE: 'milestones.create',
  MILESTONES_UPDATE: 'milestones.update',
  MILESTONES_DELETE: 'milestones.delete',
  // CMS content (W4) — the EDITOR role manages website content.
  CONTENT_READ: 'content.read',
  CONTENT_CREATE: 'content.create',
  CONTENT_UPDATE: 'content.update',
  CONTENT_DELETE: 'content.delete',
  LEADS_READ: 'leads.read',
  LEADS_UPDATE: 'leads.update',
  APPLICATIONS_READ: 'applications.read',
  APPLICATIONS_UPDATE: 'applications.update',
  CLIENTS_READ: 'clients.read',
  CLIENTS_CREATE: 'clients.create',
  CLIENTS_UPDATE: 'clients.update',
  TIMESHEETS_READ: 'timesheets.read',
  TIMESHEETS_CREATE: 'timesheets.create',
  TIMESHEETS_UPDATE: 'timesheets.update',
  INVOICES_READ: 'invoices.read',
  INVOICES_CREATE: 'invoices.create',
  TICKETS_READ: 'tickets.read',
  TICKETS_CREATE: 'tickets.create',
  TICKETS_UPDATE: 'tickets.update',
  PORTAL_READ: 'portal.read',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];
